[package]
name = "yamaquasi"
version = "0.1.0"
edition = "2021"
description = "A toy implementation of multiple polynomial quadratic sieve"
license = "BSD3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnum = { version = "0.3", features = ["numtraits"] }
num-integer = "0.1"
num-traits = "*"

[dev-dependencies]
brunch = "0.3"

[[bench]]
name = "bench"
harness = false
