[package]
name = "pymqs"
version = "0.1.0"
edition = "2021"
description = "Python bindings for yamaquasi"
license = "BSD3"
 
[lib]
name = "pymqs"
crate-type = ["cdylib"]
 
[dependencies]
pyo3 = { version = "0.18", features = ["abi3-py37", "extension-module"] }
rayon = "1.6"
yamaquasi = { path = ".." }

