# Workflows related to pymqs

name: pymqs

on: [push, pull_request]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        # macos-13 is x86, macos-14 is arm64
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

    env:
      CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
      CIBW_BEFORE_ALL_WINDOWS: rustup target add i686-pc-windows-msvc
      CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
      # freethreaded on windows seems broken
      CIBW_SKIP: cp314t-win*
      # Current min version for Rust
      MACOSX_DEPLOYMENT_TARGET: 10.12

  sdist:
    name: Source tarball
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install build
      - run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  test:
    needs: build
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04,
          ubuntu-24.04,
          ubuntu-24.04-arm,
          windows-2022,
          windows-2025,
          macos-13,
          macos-14,
          macos-15,
          #macos-26-arm64,
        ]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: false
      - uses: actions/download-artifact@v5
        with:
          path: wheelhouse
          merge-multiple: true

      # gmpy2 is missing binary wheels for Linux arm
      - run: sudo apt-get install libmpfr-dev
        if: ${{ startsWith( matrix.os , 'ubuntu' ) }}

      - run: pip install gmpy2
      - run: pip install --no-index --find-links wheelhouse pymqs
      - run: python scripts/test_general.py -j1 1 120
